language: rust

cache: cargo

branches:
  only:
    - "development"

rust:
  - stable
  - beta
  - nightly

script:
  - cargo test
  - python test_output.py

matrix:
  allow_failures:
    - rust: nightly
