language: rust

cache: cargo

install:
  - pip install -U pip setuptools
  - pip install -U pytest


branches:
  only:
    - master

rust:
  - stable
  - beta
  - nightly

script:
  - cargo test
  - py.test test_output.py

matrix:
  allow_failures:
    - rust: nightly
