[package]
name = "safari"
version = "2.0.3"
authors = ["Alex Chan <alex@alexwlchan.net>"]

[dependencies]
docopt = "0.7"
plist = "0.1"
rustc-serialize = "0.3"
tera = "0.7.2"
urlencoding = "0.2"
urlparse = "0.7.3"
