[package]
name = "safari"
version = "1.2.0"
authors = ["Alex Chan <alex@alexwlchan.net>"]

[dependencies]
clap = {version = "2.19", features = ["yaml"]}
plist = "0.1"
tera = "0.7.2"
urlparse = "0.7.3"
